spring.application.name=config-server
server.port=${SERVER_PORT:8888}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:native}
spring.cloud.config.server.native.search-locations=${CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:classpath:/config}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=${REGISTER_CONFIG_SERVER_WITH_EUREKA:true}
eureka.client.fetch-registry=${FETCH_CONFIG_SERVER_REGISTRY:true}
